config/routes.rb
Rails.application.routes.draw do
  
  get '/createBallot', to: 'ballots#new'
  get 'ballots/new'
  post 'ballots/addSelection'
  root 'application#home'
  
  get 'application/home'
  
  resources :ballots do
    resources :full_votes
  end
  

end

app/models/ballot.rb
class Ballot < ActiveRecord::Base
    has_many :selection
    has_many :full_vote
    accepts_nested_attributes_for :selection, allow_destroy: true
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
  def new
    @ballot = Ballot.new

    @ballot.selection.build
    @ballot.selection.build
    @ballot.selection.build
    
  end
  
  def addSelection
    @ballot = Ballot.new(ballot_params)
    @ballot.selection.build
    render 'new'
  end
  
  def show
    @ballot = Ballot.find(params[:id])
  end
  
  def create
    @ballot = Ballot.new(ballot_params)
    if(@ballot.save)
      redirect_to(@ballot)
    else 
      render 'new'
    end
  end
  
  def index
    @ballots = Ballot.all
  end

  
  def edit
    @ballot = Ballot.find(params[:id])
  end
  
  private
    def ballot_params
      params.require(:ballot).permit(:electioneer, :name, selection_attributes: [:name])
    end
    
end

app/helpers/ballots_helper.rb
module BallotsHelper
end

app/views/ballots/edit.html.erb
<h1>EDIT</h1>


<%= form_for(@ballot) do |ballot| %>
    <%= ballot.label "Who is making this ballot?" %>
    <%= ballot.text_field :electioneer %>
    
    <%= ballot.label "What are you voting on?" %>
    <%= ballot.text_field :name %>
    <br/>
    <%= ballot.fields_for :selection do |selection_fields| %>
        <% selection_fields.label "Write a choice:" %>
        <% selection_fields.text_field :name %>
    <% end %>
    <br/>
    <%= ballot.submit "Create a new ballot" %>
    
    
    <br/>
    <%= @ballot.selection.class %>
    <%= debug(@ballot.selection) if Rails.env.development? %>
<% end %>

app/views/ballots/index.html.erb
<h1>Current Ballots:</h1>
<ul>
    <% @ballots.each do |ballot| %>
        <li><%= link_to ballot.name, ballot_path(ballot.id) %></li>
    <% end %>
</ul>

app/views/ballots/new.html.erb
<h1>Create a new Ballot!</h1>
<p>Add selections to vote on and send this ballot to your friends:</p>

<%= form_for(@ballot) do |ballot| %>
    <p>
        <%= ballot.label "Who is making this ballot?" %>
        <%= ballot.text_field :electioneer %>
    
        <%= ballot.label "What are you voting on?" %>
        <%= ballot.text_field :name %>
    </p>
    <div class="selection">
        <%= ballot.fields_for :selection do |selection_fields| %>
            <p>
                <%= selection_fields.label "Write a choice:" %>
                <%= selection_fields.text_field :name %>
            </p>
        <% end %>
    </div>
    <p>
        <%= ballot.submit "Create a new ballot" %>
        <%= ballot.submit "Add another selection", formaction: 'addSelection'%>
    </p>
    
    <br/>

<% end %>

app/views/ballots/show.html.erb
<h3><%= @ballot.name %></h3>
<p>Ballot created by : <%= @ballot.electioneer %></p>
<ol>
    <% @ballot.selection.each do |t| %>
        <li><%= t.name %></li>
    <% end %>
</ol>

<p><%= link_to "Vote on this ballot", new_ballot_full_vote_path(@ballot) %></p>
<p><%= link_to "See votes on this ballot", ballot_full_votes_path(@ballot) %></p>